### ISSUE TITLE
Broken YouTube demo link on README page

### ISSUE THREAD

**Issue by sychoo** [korkeep/PX4-Malicious#1]
Hi I was wondering if you can fix the link for the YouTube demo on the README page? I'm excited to try out the PX4 malicious codebase but I'm not able to view the demo.

Thank you so much!

**Comment by korkeep** [comment]
**@sychoo**

I checked your comment now since I had to prepare job interview lately.
After job interview, I'll check my backup file whether I can find demo video.

Sorry for the late reply🙏

**Comment by korkeep** [comment]
@sychoo

Please check readme file again.
Thanks for leaving a comment 🤭

Link: https://github.com/korkeep/PX4-Malicious
